[package]
name = "rust_cache"
version = "0.1.0"
edition = "2021"


[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module"] }
pyo3-macros = "0.18.1"


[lib]
name = "rust_cache"
crate-type = ["cdylib"]